### ISSUE TITLE
Rest Api error

### ISSUE THREAD

**Issue by ijazm** [jbossdemocentral/brms-install-demo#20]
after containerization when i am doing a rest call i am getting an error
java.lang.ClassNotFoundException: org.guvnor.rest.client
is there something to be configured ? additionally in the docker file

**Comment by DuncanDoyle** [comment]
Can you give a bit more info on what you're doing? Are you running this in a container (Docker?). What kind of REST call are you doing. I need a bit more info to debug and help.
